### ISSUE TITLE
টপ কন্ট্রিবিউটর

### ISSUE THREAD

**Issue by zonayedpca** [devsonket/devsonket.github.io#25]
প্রতি সপ্তাহে আমরা ৪-৫জন করে টপ কন্ট্রিবিউটর সিলেক্ট করবো। তাদের নাম, তাদের গিটহাব প্রোফাইলের লিঙ্কসহ ডেভ সংকেত এর হোমপেজে থাকবে। আমি মনে করি তাহলে কিছুটা হলেও কন্ট্রিবিউটরদের কাজে আসবে ব্যাপারটা। কন্ট্রিবিউটররা তাদের প্রোফাইল সবার সামনে তুলে ধরতে পারবে। সবার মতামত আশা করছি...

**Comment by menomanabdulla** [comment]
it's really good approach. I appriciate that vai :)

On Nov 18, 2018 11:40 AM, "Zonayed Ahmed" <notifications@github.com> wrote:

প্রতি সপ্তাহে আমরা ৪-৫জন করে টপ কন্ট্রিবিউটর সিলেক্ট করবো। তাদের নাম, তাদের
গিটহাব প্রোফাইলের লিঙ্কসহ ডেভ সংকেত এর হোমপেজে থাকবে। আমি মনে করি তাহলে
কিছুটা হলেও কন্ট্রিবিউটরদের কাজে আসবে ব্যাপারটা। কন্ট্রিবিউটররা তাদের
প্রোফাইল সবার সামনে তুলে ধরতে পারবে। সবার মতামত আশা করছি...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/devsonket/devsonket.github.io/issues/25>, or mute the
thread
